[package]
name = "ytml"
version = "0.1.0"
edition = "2021"
description = "A markup language that offers a different syntax to html"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pest = "2.5.5"
pest_derive = "2.5.5"
