[package]
name = "ytml"
version = "0.1.2"
edition = "2021"
description = "A markup language that offers a different syntax to html"
license = "MIT"

[dependencies]
pest = "2.5.5"
pest_derive = "2.5.5"
