[package]
name = "inner-content"
version = "0.1.0"
edition = "2021"

[dependencies]
ytml-lang = {path = "../../packages/ytml-lang", features = ["display"]}

[[bin]]
name = "inner-content"
path = "main.rs"
