text       =  { (ASCII_ALPHANUMERIC | "-" | "!" | "_")+ }
string     = ${ "\"" ~ text ~ "\"" }
tag_name   =  { text }
prop_name  =  { text }
prop_value =  { string }
tag_props  =  { "(" ~ tag_prop+ ~ ")" }
tag_prop   =  { prop_name ~ "=" ~ prop_value }
tag_inner  =  { tag+ | text }
tag_multiplier = { "*" ~ ASCII_DIGIT+}
tag        =  { tag_name ~ tag_multiplier? ~ tag_props? ~ "{" ~ tag_inner? ~ "}" }

doc = { SOI ~ tag* ~ EOI }

WHITESPACE = _{ " " | "\n" }
